version: "3.8"

services:
  juno_plugin:
    volumes:
      - type: bind
        source: $HOME/snapshots/
        target: /snapshots
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      VAULT_HASH: ${VAULT_HASH}
      UDC_ADDRESS: ${UDC_ADDRESS}
      VAULT_ADDRESS: ${VAULT_ADDRESS}
      L1_URL: ${L1_URL}
      DB_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "6060:6060" # Adjust this port if needed

volumes:
  postgres_data:
