version: "3.8"

services:
  pitchlake_db:
    image: postgres:16
    environment:
      POSTGRES_DB: pitchlake_db
      POSTGRES_USER: pitchlake_user
      POSTGRES_PASSWORD: pitchlake_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pitchlake_user -d pitchlake_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  juno_plugin:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_URL: postgres://pitchlake_user:pitchlake_password@pitchlake_db:5432/pitchlake_db
    depends_on:
      pitchlake_db:
        condition: service_healthy
    ports:
      - "6060:6060" # Adjust this port if needed

volumes:
  postgres_data:
