DROP TABLE IF EXISTS public."Liquidity_Providers";
DROP FUNCTION IF EXISTS public.notify_lp_update();
DROP TRIGGER IF EXISTS lp_update ON public."Liquidity_Providers";
DROP TABLE IF EXISTS public."Option_Rounds";
DROP FUNCTION IF EXISTS public.notify_or_update();
DROP TRIGGER IF EXISTS or_update ON public."Option_Rounds";
DROP TABLE IF EXISTS public."Queued_Liquidity";
DROP FUNCTION IF EXISTS public.notify_vault_update();
DROP TRIGGER IF EXISTS vault_update ON public."VaultStates";
DROP TABLE IF EXISTS public."Option_Buyers";
DROP FUNCTION IF EXISTS public.notify_ob_update();
DROP TRIGGER IF EXISTS ob_update ON public."Option_Buyers";
DROP TABLE IF EXISTS public."Bids";
