name: Juno Plugin CI

on:
  push:
    branches:
      - main
      - feat/ci_juno
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.1
      
      - name: Check Code Formatting
        run: |
          echo "Checking formatting with go fmt..."
          go fmt ./... || exit 1
          echo "Formatting checked successfully!"

      - name: Build Juno
        run: |
          echo "Building Juno..."
          cd juno
          make juno
          cd ..

      - name: Build Plugin
        run: |
          echo "Building Juno Plugin..."
          make build
          ls -al build

      - name: Validate Plugin Build
        run: |
          echo "Validating the plugin .so file..."
          if [ ! -f "./build/myplugin.so" ]; then
            echo "Error: Plugin .so file not found!"
            exit 1
          fi
