name: Juno Plugin CI

# Trigger the workflow on push events specifically for the 'master' branch
on:
  push:
    branches:
      - main
      - feat/fix_ci
  # pull_request:
  #   branches:
  #     - main

jobs:
  build:
    name: Building CI pipeline on Ubuntu OS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.1

      # - name: Install jemalloc
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y libjemalloc-dev

      - name: Check Code Formatting
        run: |
          echo "Checking formatting with go fmt..."
          go fmt ./... || exit 1
          echo "Formatting checked successfully!"

      - name: Build Juno
        run: |
          echo "Building Juno..."
          cd juno
          make build
      