name: Juno Plugin CI

# Trigger the workflow on push events specifically for the 'master' branch
on:
  push:
    branches:
      - feat/fix_ci

jobs:
  build:
    # Set the job name and specify it runs on the latest Ubuntu virtual environment
    name: Building CI pipeline on Ubuntu OS
    runs-on: ubuntu-latest

    steps:
      # Step to check out the code from the Git repository so that it can be used in subsequent steps
      - name: Checkout code
        uses: actions/checkout@v2

      # Step to update any Git submodules recursively, ensuring that any dependent repositories are also up to date
      - name: Update submodules
        run: git submodule update --init --recursive

      # Step to set up Go
      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.1

      - name: Install jemalloc
        run: |
          sudo apt-get update
          sudo apt-get install -y libjemalloc-dev

      # Step to check code formatting
      - name: Check Code Formatting
        run: |
          echo "Checking formatting with go fmt..."
          go fmt ./... || exit 1
          echo "Formatting checked successfully!"
          
      # Step to build Juno
      - name: Build Juno
        run: |
          echo "Building Juno..."
          cd juno
          make juno

      - name: Build Plugin
        run: |
          echo "Building Juno Plugin..."
          make build
          ls -al build

      - name: Validate Plugin Build
        run: |
          echo "Validating the plugin .so file..."
          if [ ! -f "./build/myplugin.so" ]; then
            echo "Error: Plugin .so file not found!"
            exit 1
      